name: Develop branch push
on:
  push:
    branches:
      - develop

jobs:
  publish-dev-client-library:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.CI_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CI_AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Generate typescript client library & publish to AWS Codeartifact
        run: |
          npm i @openapitools/openapi-generator-cli json -g
          # apt-get -f install openjdk-8-jre
          VERSION=$(poetry version -s)
          openapi-generator-cli generate -g typescript-axios -i swagger.json -o typescript-client --model-package models --api-package api --additional-properties=npmVersion=$VERSION,npmName=exampleClient,nullSafeAdditionalProps=true,withSeparateModelsAndApi=true,useSingleRequestParameter=true
          cd typescript-client
          aws codeartifact login --tool npm --domain octopuswealth --repository client
          npm version prerelease --preid dev.$(date +"%Y%m%d%H%M%S") 
          json -I -f package.json -e "this.files=[\"/dist/**\"]"
          npm install --registry https://registry.npmjs.org
          npm run build
          # npm publish