name: Bump version
on:
  push:
    branches:
      - main

jobs:
  publish-client-library:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
        with:
          fetch-depth: 0
          token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.CI_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CI_AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Setup python
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      #----------------------------------------------
      #  -----  install & configure poetry  -----
      #----------------------------------------------
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Configure git
        run: |
          git config --local user.name 'Aaron Elijah'
          git config --local user.email 'AaronElijah@users.noreply.github.com'
          git config --local pull.rebase true

      - name: Create and push tag
        run: |
          VERSION=$(poetry version -s)
          git tag $VERSION
          INPUT_BRANCH=${{ github.ref_name }}
          GITHUB_ACTOR=${{ github.actor }}
          INPUT_GITHUB_TOKEN=${{ secrets.PAT }}
          INPUT_REPOSITORY=${{ github.repository }}
          REMOTE_REPO="https://${GITHUB_ACTOR}:${INPUT_GITHUB_TOKEN}@github.com/${INPUT_REPOSITORY}.git"
          git push "$REMOTE_REPO" "HEAD:${INPUT_BRANCH}" --tags

      - name: Generate typescript client library & publish to AWS Codeartifact
        run: |
          npm i @openapitools/openapi-generator-cli json -g
          # apt-get install openjdk-8-jre
          VERSION=$(poetry version -s)
          openapi-generator-cli generate -g typescript-axios -i swagger.json -o typescript-client --model-package models --api-package api --additional-properties=npmVersion=$VERSION,npmName=exampleClient,nullSafeAdditionalProps=true,withSeparateModelsAndApi=true,useSingleRequestParameter=true
          cd typescript-client
          aws codeartifact login --tool npm --domain octopuswealth --repository client
          json -I -f package.json -e "this.files=[\"/dist/**\"]"
          npm install --registry https://registry.npmjs.org
          npm run build
          npm publish