name: Verify Release ID
on:
  pull_request:
    branches:
      - master

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
        with:
          fetch-depth: 0
          token: "${{ secrets.GITHUB_TOKEN }}"

      # potential bit of confusion here because this creates a tag that is pushed to origin repo
      # however this will not trigger a release flow for tags
      # hence the actual build of the client library is in main branch
      # so the tag is created, then the release pr is merged, then the client library is published.
      - id: cz
        name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Print Version
        run: echo "Bumped to version ${{ steps.cz.outputs.version }}"
