name: Prepare release
on:
  push:
    branches:
      - "release/*"

jobs:
  bump-version:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.9' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
        with:
          fetch-depth: 0
          token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Get tags
        run: |
          git fetch --tags

      - name: Configure git
        run: |
          git config --local user.name 'Aaron Elijah'
          git config --local user.email 'AaronElijah@users.noreply.github.com'
          git config --local pull.rebase true

      - name: Setup python
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      #----------------------------------------------
      # this creates a tag that is NOT pushed to origin
      # the commit SHAs change on rebase to main, making tags created on this branch
      # point to commits that don't exist
      #----------------------------------------------
      - name: Bump version
        run: |
          pip install commitizen
          cz bump --changelog --check-consistency --annotated-tag
          INPUT_BRANCH=${{ github.ref_name }}
          GITHUB_ACTOR=${{ github.actor }}
          INPUT_GITHUB_TOKEN=${{ secrets.PAT }}
          INPUT_REPOSITORY=${{ github.repository }}
          REMOTE_REPO="https://${GITHUB_ACTOR}:${INPUT_GITHUB_TOKEN}@github.com/${INPUT_REPOSITORY}.git"
          git push "$REMOTE_REPO" "HEAD:${INPUT_BRANCH}"
